---
title: "Neighborhood Exploratory Graphics"
date: "Generated: `r Sys.Date()`"
runtime: shiny
output:
    html_document:
        toc: true
        toc_depth: 3
        theme: spacelab
        highlight: zenburn
        number_sections: false
---

```{r global_opts, include=FALSE}
knitr::opts_chunk$set(fig.path='./Figs', echo=FALSE, warning=FALSE, message=FALSE,
                    dev='svg')
```
-------------------

# Info
* [code](https://github.com/ghandi9000/hoods)
* Basic neighbor relationship to target: BA / Distance, negative exponential decrease?
* Ways to __quantify__ a neighborhood (possibly relative to target size where applicable):
    + Sum total neighbor values (ie. BA/Distance)
    + Max neighbor value
    + Mean/median neighbor value
    + Number of neighbors
    + Avg. distance
    + Avg. weighted distance (same as mean neighbor value maybe)
    + Species proportions
* Ways to __assess__ effects of neighborhood value on target:
    + [DBH, Height, BV, BA] Growth
    + Ratios [Height/BA, ...]
    + Species
    + Decline index

---------------------

# Setup 
* Neighbor radii:
    + `1` is just the quadrat containing target
    + `2` is 3x3 (2 quadrats in all directions from target, including target's quadrat)
    + `3` is 5x5

```{r setup}

require(xtable)

source("setup.R")
source("hood_functions.R")

## Total target sample size
nbrs <- pp %>% group_by(YEAR, PPLOT) %>%
  filter(STAT == "ALIVE",
         !is.na(BQUDX), BQUDX > 0, BQUDX < 11,
         !is.na(BQUDY), BQUDY > 0, BQUDY < 11,
         !is.na(DBH))
# 
# sampleSize <- nbrs %>%
#   summarise(Total = n())

renderText({ "Total Sample Sizes by Plot/Year:"})
renderTable({
  sampleTable <- table(nbrs$YEAR, nbrs$PPLOT)
  addmargins(sampleTable) #, caption = "Total sample sizes")
})
```

```{r shiny_vars, cache=FALSE}
require(magrittr)
require(dplyr)
require(ggplot2)

selectInput("nRad", "Choose Neighbor Radius:",
            choices=c(1, 2, 3))
nRad <- reactive(as.numeric(input$nRad))  # get neighbor radius from input
nMat <- reactive({
    rad <- nRad()
    if (file.exists(paste0("temp/nm", rad, ".rds"))) readRDS(paste0("temp/nm", rad, ".rds"))
    else {
        nLst <- mnm(tPars = tPars, nPars = nPars, dPars = dPars, nCols = nCols,
                    nRad = rad, dat = matDat, parallel=F)
        nmat <- mnm_to_matrix(nLst)
        saveRDS(paste0("temp/nm", rad, ".rds"))
        nmat
    }
})

renderText({
    paste("Target sample sizes with neighbor radius:", nRad())
})

renderTable({
    nmat <- nMat()  # make neighbor matrices  
    targetTable <- table(nmat$targets$time, nmat$targets$pplot)
    addmargins(targetTable) #, caption = "Target sample sizes")
})

## Neighbor counts
selectInput("splitBy", "Split counts by:",
            choices=c("Don't split", "Aspect", "Elevation", "Plot"))
splitBy <- reactive({
  if (input$splitBy == "Aspect") "aspcl"
  else if (input$splitBy == "Elevation") "elevcl"
  else if (input$splitBy == "Plot") "pplot"
  else FALSE
})

nCounts <- reactive({ nm <- nMat(); rowSums(!is.na(nm$ba) )})
renderPlot({
  sp <- splitBy()
  r <- nRad()
  nm <- nMat()
  counts <- nCounts()
  if (sp != FALSE)
    ggplot(cbind(counts=counts, nm$targets), aes(counts)) +
    geom_histogram() + 
    facet_wrap(as.formula(paste("~", sp))) +
    ggtitle(paste0("Histograms of Neighbor Counts(radius=", r, ")"))
  else
    hist(counts, main=paste0("Histogram of Neighbor Counts (radius=", r, ")"))
})

# renderPlot({
#     nmat <- nMat()
#     ggplot(nmat$targets, aes(ba)) + geom_histogram()
# })

```

# Plot-Level Distributions
Look more closely at specific plots and the distributions of targets/neighbors.
```{r plot_distributions, cache=FALSE}

sidebarLayout(
  
  sidebarPanel(
    helpText("Choose individual plot for closer inspection."),
    selectInput("plot", "Choose Plot:", choices=unique(pp$PPLOT)),
    br(),
    selectInput("type", "Plot Type:", 
                choices=c("Histogram", "Position", "Density", "Scatter")),
    conditionalPanel(
      condition = "input.type == 'Scatter'",
      selectInput("yVar", "Y", choices=c("HT", "HTOBS", "DBH", "BV", "BA")),
      selectInput("xVar", "X", choices=c("DBH", "BV", "BA", "HT", "HTOBS")),
      selectInput("splitScatter", "Split:", 
                  choices=c("None", "CANHT", "SPEC")),
      conditionalPanel(
          condition = "input.yVar == 'HT' && input.xVar == 'DBH'",
          checkboxInput("showFit", "Show fitted")
        ),
      checkboxInput("smoother", "Add smoothed spline"),
      conditionalPanel(
        condition = "input.smoother == true",
        selectInput("smoothMethod", "Method",
              list("loess", "lm", "glm", "gam", "rlm"))
        )
      ),
    conditionalPanel(
      condition = "input.type == 'Position'",
      checkboxInput("colorTargets", "Color Targets")
      ),
    checkboxInput("chooseSpec", "Choose Species"),
    conditionalPanel(
      condition = "input.chooseSpec == true",
      checkboxGroupInput("spec", "Species:", choices=c(levels(pp$SPEC)), selected=c("ABBA"))
      ),
    br(),
    checkboxInput("targets", "Just Targets"),
    downloadButton("saveButton1", "Save")
    ),
      
  mainPanel(  
    
    renderPlot({
      plot <- as.numeric(input$plot)
      r <- nRad()
      nm <- nMat()
      species <- levels(pp$SPEC)
      if (input$chooseSpec) species <- input$spec
      nmInds <- nm$targets$pplot == plot & nm$targets$spec %in% species
      ppInds <- pp$PPLOT == plot & pp$STAT == "ALIVE" & pp$SPEC %in% species
      
      if (input$targets) 
        ppInds <- ppInds & pp$id %in% nm$targets[nmInds, "id"]
      
      #########################################################
      ##                      Plot types                     ##
      #########################################################
      if (input$type == "Histogram") {
        counts <- rowSums(!is.na(nm$ba[nmInds,]))
        p1 <- ggplot(cbind(counts=counts, nm$targets[nmInds,]), aes(counts)) +
          geom_histogram() + facet_wrap(~time) +
          ggtitle(paste0("Histograms of Neighbor Counts(radius=", r, "), Plot=", plot))
 
      } else if (input$type == "Density") {
        specs <- pp[ppInds,] %>% group_by(SPEC, YEAR) %>% filter(n() > 2)
        p1 <- ggplot(specs, aes(BQUDX, BQUDY, size=BA, color=SPEC)) + 
          geom_density2d(na.rm=TRUE) + facet_wrap(~YEAR) +
          ggtitle("Species Densities (removed species with counts <= 2)")
        
      } else if (input$type == "Position") {
        p1 <- ggplot(pp[ppInds,], aes(BQUDX, BQUDY, size=BA, color=SPEC)) +
          geom_point(alpha=0.5) +
          facet_wrap(~YEAR) + xlim(0.8, 10.2) + ylim(0.8, 10.2) + 
          geom_hline(yintercept=c(1, 10), lty=2) +
          geom_vline(xintercept=c(1, 10), lty=2)
        
        if (input$colorTargets) {
          inds <- pp$PPLOT == plot & pp$STAT == "ALIVE" & 
            pp$id %in% nm$targets[nmInds, "id"]
          
          p1 <- p1 + geom_point(data=pp[inds,], 
                                aes(BQUDX, BQUDY), color="red")
          }
        
      } else if (input$type == "Scatter") {
        p1 <- ggplot(pp[ppInds,], 
                     aes_string(input$xVar, input$yVar, color="YEAR")) + 
          geom_point(alpha=0.5) +
          ggtitle(paste(input$yVar,"vs", input$xVar, ", Plot=", plot))
        
        if (input$splitScatter != "None")
          p1 <- p1 + facet_wrap(as.formula(paste("~", input$splitScatter)))
        
        if (input$smoother) 
          p1 <- p1 + geom_smooth(fill=NA, method=input$smoothMethod)
        
        if (input$showFit) {
          inds <- ppInds & is.na(pp$HTOBS)
          p1 <- p1 + geom_line(data=pp[inds,], aes(DBH, HT, color=YEAR))
          }
        }
      
      print ( p1 )
      
      ## Saving graphs
      output$saveButton1 <-
        downloadHandler(
          filename = paste0(gsub("[: ]", "_", input$type), "_plot_", 
                            plot, "_radius_", r, ".png"),
          content = function(file) {
            device <- function(..., width, height) {
              grDevices::png(..., width=width, height=height,
                             res=300, units="in")
              }
          ggsave(file, plot=p1, device=device)
          })
      })
    
    )
)

```


---------------------

# Neighborhoods and Growth
Examine various ways of estimating neighborhood values and look, visually, at the effect on growth.

```{r hoods_growth, cache=FALSE}
require(grid)

sidebarLayout(
  
  sidebarPanel(
    helpText("Choose individual plot for closer inspection."),
    selectInput("plot2", "Choose Plot:", choices=unique(pp$PPLOT)),
    br(),
    selectInput("type2", "Plot type:", 
                choices=c("Vector Growth", "Neighbor Count", "Histogram", "etc")),
    conditionalPanel(
      condition = "input.type2 == 'Histogram'",
      helpText("Binning variable, g means _Growth_"),
      selectInput("histVar", "X", choices=c("gDBH", "gHT", "gHTOBS", "gBV", "gBA"))
      # sliderInput("binWidth", "Binwidth", min=0.00001, max=.05, value=0.03, step=0.0001)
      ),
    conditionalPanel(
      condition = "input.type2 == 'Neighbor Count'",
      checkboxInput("nCountVector", "Vector", FALSE),
      conditionalPanel(
        condition = "input.nCountVector == true",
        selectInput("nCountVectorY", "Y", choices=c("HT", "HTOBS", "DBH", "BV", "BA"))
        ),
      conditionalPanel(
        condition = "input.nCountVector == false",
        selectInput("nCountY", "Y", choices=c("gHT", "gHTOBS", "gDBH", "gBV", "gBA"))
        )
      ),
    conditionalPanel(
      condition = "input.type2 == 'Vector Growth'",
      selectInput("yVar2", "Y", choices=c("HT", "HTOBS", "DBH", "BV", "BA")),
      selectInput("xVar2", "X", choices=c("DBH", "BV", "BA", "HT", "HTOBS")),
      selectInput("splitScatter2", "Split:", 
                  choices=c("None", "SPEC")),
      checkboxInput("addPoints", "Points"),
      conditionalPanel(
        condition = "input.yVar2 == 'HT' && input.xVar2 == 'DBH'",
        checkboxInput("showFit2", "Show fitted")
        ),
      checkboxInput("smoother2", "Add smoothed spline"),
      conditionalPanel(
        condition = "input.smoother2 == true",
        selectInput("smoothMethod2", "Method",
                    list("loess", "lm", "glm", "gam", "rlm"))
        )
      ),
    checkboxInput("chooseSpec2", "Choose Species"),
    conditionalPanel(
      condition = "input.chooseSpec2 == true",
      checkboxGroupInput("spec2", "Species:", choices=c(levels(pp$SPEC)), selected=c("ABBA"))
      ),
    checkboxInput("onlyTargets", "Targets only"),
    downloadButton("saveButton2", "Save")
    ),

  mainPanel(
    
    renderPlot({
      plot <- as.numeric(input$plot2)
      r <- nRad()
      nm <- nMat()
      species <- levels(pp$SPEC)
      if (input$chooseSpec2) species <- input$spec2
      nmInds <- nm$targets$pplot == plot & nm$targets$spec %in% species
      ppInds <- pp$PPLOT == plot & pp$STAT == "ALIVE" & pp$SPEC %in% species
      
      if (input$onlyTargets) 
        ppInds <- ppInds & pp$id %in% nm$targets[nmInds, "id"]
      
      #########################################################
      ##                      Plot types                     ##
      #########################################################
      if (input$type2 == "Vector Growth") {
        p1 <- ggplot(pp[ppInds,], aes_string(input$xVar2, input$yVar2, color="YEAR")) + 
          geom_path(alpha=0.5, aes(group=id), arrow=arrow(), na.rm=TRUE) +
          ggtitle(paste0("Vector Growth, Plot=", plot))
        
        if (input$addPoints)
          p1 <- p1 + geom_point(alpha=0.3, na.rm=TRUE)
        
        if (input$splitScatter2 != "None")
          p1 <- p1 + facet_wrap(as.formula(paste("~", input$splitScatter2)))
        
        if (input$smoother2) 
          p1 <- p1 + geom_smooth(fill=NA, method=input$smoothMethod2, na.rm=TRUE)
        
        if (input$showFit2) {
          inds <- ppInds & is.na(pp$HTOBS)
          p1 <- p1 + geom_line(data=pp[inds,], aes(DBH, HT, color=YEAR), lwd=2, na.rm=TRUE)
          }
        
        } else if (input$type2 == "Vector Growth: Neighbor Count") {
          tPars <- gsub("ba", "BA", deparse(attributes(nm)$target_par))
          inds <- ppInds & pp$id %in% nm$targets[nmInds, "id"] & 
            eval(parse(text = tPars), pp)
          counts <- rowSums(!is.na(nm$ba[nmInds,]))
          
          if (input$nCountVector)
            p1 <- ggplot(cbind(pp[inds,], counts=counts), aes_string("counts", input$nCountVectorY)) +
            geom_point(na.rm=TRUE) + 
            geom_path(alpha=0.5, aes(group=id), arrow=arrow(), na.rm=TRUE)
          
          if (input$nCountY)
            p1 <- ggplot(cbind(pp[inds,], counts=counts), aes_string("counts", input$nCountY)) +
            geom_point(na.rm=TRUE)
        
        } else if (input$type2 == "Histogram") {
          p1 <- ggplot(pp[ppInds,], aes_string(input$histVar)) + 
            geom_histogram() # binwidth=as.numeric(input$binWidth))
          
        } else {
          ## Do nothing
        }
      
      print ( p1 )
      
      ## Saving graphs
      output$saveButton2 <-
        downloadHandler(
          filename = paste0(gsub("[: ]", "_", input$type2), "_plot_", 
                            plot, "_radius_", r, ".png"),
          content = function(file) {
            device <- function(..., width, height) {
              grDevices::png(..., width=width, height=height,
                             res=300, units="in")
              }
          ggsave(file, plot=p1, device=device)
          })
      
      })
    )
  )


```


---------------------

# Permanent Plots

---------------------

# Transect Plots
